#zuul 路由配置可以省略，缺省以服务 id 作为访问路径
spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.161.139
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true

#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream